### ISSUE TITLE
[Bug]: Regression in simulation colour parameter

### ISSUE THREAD

**Issue by kyubxy** [techlauncher-mlai-edge-physics/CFlowSim#138]
**Describe the bug**
Changing the simulation colour breaks the renderer and the plane remains a solid colour.

**To Reproduce**

1. run the simulation
2. while the simulation is running, change either the high or low colour
3. the simulation now halts. further inspection shows that the model is still producing output as expected.

**Expected behavior**
The simulation continues rendering with the newly set colours.

**Screenshots**
[this video](https://www.youtube.com/watch?v=_esIksJCzNM) should give a better idea as to what is going on.

**Desktop (please complete the following information):**

- OS: arch linux `6.4.11-arch2-1`
- Browser: chrome (stable)
- Version 116.0.5845.179 (Official Build) (64-bit)

**Additional context**
Evident from the abundance of console logs dumped every frame, this is definitely the fault of the simulator and not the model.

Once again, this could very well be a linux problem as well. Someone please confirm they can repro on another OS.

**Task Relationship**
  Belongs to: #<--issue number-->
  Blocks: #<--issue number-->
  Blocked by: #<--issue number-->
  Subtasks: #<--issue number-->

**Comment by Lutra-Fs** [comment]
See #136 Highly Possibly related
