### ISSUE TITLE
[Deliverable] Site analytics

### ISSUE THREAD

**Issue by peipacut** [techlauncher-mlai-edge-physics/CFlowSim#31]
Implement analytics tracking onto the website to track anonymous data about users. The data should be viewable via a private dashboard.

## Success criteria
- Given that a user has never accessed the website before, when they open the webpage, the relevant statistics change.
- A dashboard is produced which accurately collects data.
- Our client verifies that the sort of data that is being collected is okay.

## Task Relationship
  - Belongs to: #<--issue number-->
  - Blocks: #<--issue number-->
  - Blocked by: #<--issue number-->
  - Subtasks: #<--issue number-->

**Comment by LorenzoValentine** [comment]
Now waiting for the administrator to add my account to management.

**Comment by Lutra-Fs** [comment]
internally blocked by https://discord.com/channels/1078235779408592956/1079250089295491113/1150676236792758275
