### ISSUE TITLE
add more content to about page

### ISSUE THREAD

**Issue by Lutra-Fs** [techlauncher-mlai-edge-physics/CFlowSim#40]

**Comment by peipacut** [comment]
this is complete when
- about page is restyled
- links are added to landing page and github
- changes are reviewed and merged

**Comment by Lutra-Fs** [comment]
> - about page is restyled
if the page needs to be restyled, The title and what is in the deliverable should be restyled about page. Code change can be covered but this issue and linked pr should focus on what is in the document.
