### ISSUE TITLE
store model data to file

### ISSUE THREAD

**Issue by Lutra-Fs** [techlauncher-mlai-edge-physics/CFlowSim#70]
as a user I want to save my model data to a file accessible offline

## success criteria:
- all tests pass
- given that the model is running, when the user invokes the save mechanism, the simulator stores the information in the model some source that could be read in the future

## Task Relationship
  - Belongs to: #30
  - Blocks: #<--issue number-->
  - Blocked by: #<--issue number-->
  - Subtasks: #<--issue number-->

**Comment by peipacut** [comment]
user story points: 2.5
