### ISSUE TITLE
restore model data from source

### ISSUE THREAD

**Issue by Lutra-Fs** [techlauncher-mlai-edge-physics/CFlowSim#71]
as a user, I want to restore a model state I previously saved

## success criteria:
- all tests pass
- when the user presses the load button and selects the save, the model will restore the state and continue running

## Task Relationship
  - Belongs to: #30 
  - Blocks: #<--issue number-->
  - Blocked by: #<--issue number-->
  - Subtasks: #<--issue number-->

**Comment by peipacut** [comment]
user story points: 2.5

**Comment by Lutra-Fs** [comment]
@peipacut may I take this issue? as #98 has been closed
