### ISSUE TITLE
explore the various options that the data could be saved and restored

### ISSUE THREAD

**Issue by Lutra-Fs** [techlauncher-mlai-edge-physics/CFlowSim#72]
## Success Criteria
- figma designs

## Task Relationship
  - Belongs to: #<--issue number-->
  - Blocks: #<--issue number-->
  - Blocked by: #<--issue number-->
  - Subtasks: #<--issue number-->

**Comment by Lutra-Fs** [comment]
there are several options as a reference
- automatically store
- ask user to store when user exit the website
- user needs to manually store the data

As we are adding tensorflowjs runtime provider, the saved data should also contains related info like which model has been choosen to generate the saved data.

**Comment by LorenzoValentine** [comment]
What will do:
automatically store
ask user to store when user exit the website
user needs to manually store the data

Current Stage: UI design(for any possible)
