### ISSUE TITLE
port GLSL shaders to WGSL

### ISSUE THREAD

**Issue by Lutra-Fs** [techlauncher-mlai-edge-physics/CFlowSim#79]
## Success criteria
- WGSL shader can have the same effect with the GLSL texture

## Task Relationship
  - Belongs to: #32
  - Blocks: #<--issue number-->
  - Blocked by: #<--issue number-->
  - Subtasks: #<--issue number-->

**Comment by peipacut** [comment]
user story points: 8

**Comment by peipacut** [comment]
not looking feasible at this stage, might have to cancel
