### ISSUE TITLE
design UI to choose between backends/models/initial conditions

### ISSUE THREAD

**Issue by peipacut** [techlauncher-mlai-edge-physics/CFlowSim#96]
success criteria: figma screenshots

**Comment by peipacut** [comment]
user story points: 3

**Comment by LorenzoValentine** [comment]
https://www.figma.com/file/GeF36gAGL2sbsPbqKAVIQQ/physics-in-the-browser-final?type=design&node-id=422-179&mode=design&t=RMe7bFM2qRE3u4h7-0
