### ISSUE TITLE
study webgpu in threejs and how to use it in the renderer

### ISSUE THREAD

**Issue by peipacut** [techlauncher-mlai-edge-physics/CFlowSim#97]
success criteria: document

**Comment by peipacut** [comment]
user story points: 3

**Comment by peipacut** [comment]
to be done by tuesday

**Comment by Lutra-Fs** [comment]
It is now Tuesday. Any updates on this issue?

**Comment by peipacut** [comment]
To avoid blocking progress on the webgpu port we won't be putting in anymore effort into this task specifically. the actual report will be an ongoing effort while we actually implement the webgpu changes, I propose we close this issue.
